# General  
train_2d: True
has_3d: False
no_eval: True
finetune: False
partial_train: null
phase: 'test'
# Traning 
epochs: 100
checkpoint_frequency: 30
batch_size: 96
dropout: 0.1
learning_rate: 0.0003 # NOTE: this was 0.0005 in the original config
weight_decay: 0.01
lr_decay: 0.99
pretrain_3d_curriculum: 30

# Model
maxlen: 120
dim_feat: 128
mlp_ratio: 2
depth: 4
dim_rep: 256
hidden_dim: 256
num_heads: 8
att_fuse: True

# model for embeddings
pretrained: 'temp_models/epoch=44.ckpt'
model_args:
  modalities: ['skeleton']
  fusion: 'unimodal'
  feat_dim: 128
  w2v2_type: 'multilingual'
  skeleton_backbone: 'jointsformer'
  hidden_dim: 256
  attentive_pooling: True
  attentive_pooling_skeleton: True
  bertje_dim: 768
  freeze_bertje: True
  cross_modal: False
  one_branch_cross_modal: False
  multimodal_embeddings_dim: 1024
  apply_cnn: False
  maxlen: 120


modalities: ['skeleton'] # 'speech', 'skeleton', 'semantic', 'image'
loss_type: ['cross_entropy'] #  ['mm_contrastive', 'contrastive', 'masked_reconstruction', 'masked_reconstruction_contrastive']
use_contrastive: True
temp: 0.1
freeze_bertje: True
bertje_dim: 768
